state = {
    'connection' : False,
    'bee_state' : 'OFF', # OFF, READY, ATACK
    'roll': 1500,
    'pitch': 1500,
    'yaw': 1500,
    'throttle': 1100,
    'last_manual_roll': 1500,
    'last_manual_pitch': 1500,
    'last_manual_yaw': 1500,
    'last_manual_throttle': 1100,
    'aux3': 1000,
    'aux4': 1000,
    'aux5': 1000,
    'aux6': 1000,
    'aux7': 1500,
    'battery': 0,
    'rssi':0,
    'rssi_msg':'No signal',
    'speed': 0,
    'altitude': 0,
    'caught': False,
    'ready_hold_active': False,
    'ready_hold_pending_capture': False,
    'ready_hold_roll': 1500,
    'ready_hold_pitch': 1500,
    'ready_hold_yaw': 1500,
    'ready_hold_throttle': 1100,
    'target_locked': False,
    'tracking_bbox': None,
    'attack_error_x': 0.0,
    'attack_error_y': 0.0,
    'target_size': 0.0,
    'attack_active': False,
    'attack_base_roll': 1500,
    'attack_base_pitch': 1500,
    'attack_base_yaw': 1500,
    'attack_base_throttle': 1100,
    'attack_output_roll': 1500,
    'attack_output_pitch': 1500,
    'attack_output_yaw': 1500,
    'attack_output_throttle': 1100,
    'prev_attack_error_x': 0.0,
    'prev_attack_time': None,
    'prev_target_size': 0.0,
}