companion_computer = '/dev/serial0' # COM3 (for Windows)
companion_baud_rate = 115200
logger_name = 'BEE-EPT-UA913'
logger_directory = '/home/obriy/CHASE/CLEAN_NORMAL_STRUCT/autopilot_bee_ept/logs'  # logs (for Windows) 


default_roll = 1500
default_pitch = 1500
default_yaw = 1500
default_throttle = 1000
default_servo_aux2 = 1000

telemetry_off_interval = 2.0
telemetry_ready_rc_interval = 0.1
telemetry_ready_status_interval = 1.0
telemetry_attack_rc_interval = 0.1
telemetry_attack_status_interval = 1.0
telemetry_attack_imu_interval = 0.1
telemetry_ready_imu_interval = 0.1
telemetry_scheduler_interval = 0.1
ready_hold_loop_interval = 0.1
attack_loop_interval = 0.1
attack_roll_gain = 100
attack_pitch_gain = 60
attack_max_pitch_deg = 15.0
attack_yaw_gain = 150
attack_yaw_N = 3.5
attack_throttle_gain = 80
attack_throttle_brake = 0.1
attack_deadzone = 0.1
attack_aim_offset_y = 0.1
attack_terminal_size = 15000
attack_terminal_pitch_boost = 250
attack_terminal_throttle_drop = 50
attack_terminal_yaw_damping = 0.5
attack_roll_max_step = 15
attack_pitch_max_step = 5
attack_yaw_max_step = 12
attack_throttle_max_step = 10
tracking_fullscreen = True